:clients:
  - :name: Jabong
    :email: admin@jabong.com
    :password: user
    :admin: false
    :rate-limiting:
      :day: 100000
      :minute: 100
      :second: 100
      :hour: 10000
      :month: 100000
      :year: 1000000000
  - :name: Octo
    :email: api@octo.ai
    :password: admin
    :admin: true
:apis:
  - :name:  events
    :request_path: /events
    :upstream_url: http://127.0.0.1:9001/events
  - :name:  UpdatePushToken
    :request_path: /update_push_token
    :upstream_url: http://127.0.0.1:9001/update_push_token
  - :name: UpdateProfile
    :request_path: /update_profile
    :upstream_url: http://127.0.0.1:9001/update_profile
  - :name: Product
    :request_path: /product
    :upstream_url: http://127.0.0.1:9001/product
:plugins:
  :key-auth:
    :apis:
      - :events
      - :UpdatePushToken
      - :UpdateProfile
      - :Product
    :clients: all
    :config:
      :key_names: apikey
  :cors:
    :apis:
      - :events
      - :UpdatePushToken
      - :UpdateProfile
      - :Product
    :clients: all
    :config:
      :methods: 'GET,POST,PATCH,DELETE'
      :origin: '*'
  :rate-limiting:
    :apis:
      - :events
    :clients:
      - Jabong
:kong: 127.0.0.1:8001
